### ISSUE TITLE
Question about the compilation of cartographer  

### ISSUE THREAD

**Issue by Krada-Jhin** [xuankuzcr/Cartographer_ICRA#1]
想询问下,如果对于cartographer本身如何在IDE下进行修改和编译呢(测试过,其不能通过cmakelist在IDE中编译运行)

**Comment by xuankuzcr** [comment]
只要你catkin_make过了的话，roboware可以直接编译运行啊，vscode需要配置一下

**Comment by xuankuzcr** [comment]
只要你catkin_make过了的话，roboware可以直接编译运行啊，vscode需要配置一下

**Comment by Krada-Jhin** [comment]
额,可是cartographer官方版本似乎不能直接进行catkin_make(测试过),[官方文档](https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html)中要求catkin_make_isolated.我目前是按照文档要求用install的方式安装的.请问你们是怎么让其可以catkin_make的呢,之前我找到网上有个indigo版本的裁剪cartographer可以这样,不过这块我不是很明白.

**Comment by xuankuzcr** [comment]
把IDE的.json里面运行的组合命令中的catkin_make，改成catkin_make_isolated
